/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * ../TestDison.h.
 */

public class Constants  {
    public static final short AM_DISON_STATS = 146;
    public static final short DEFAULT_SAMPLING_PERIOD = 5000;
    public static final byte COMMAND_DIS_KEY = 49;
    public static final byte SINK_ID = 0;
    public static final int DEBUG_TIME = 240000;
    public static final byte NREADINGS = 1;
    public static final byte ELECTION_CYCLE_TIME = 1;
    public static final short DEFAULT_SLEEP_DUTY_CYCLE = 2000;
    public static final short DEFAULT_MIN_INTERVAL = 5000;
    public static final byte NUM_SENSORS = 2;
    public static final short AM_DISON_TOPO = 147;
    public static final byte SENSOR_HUMIDITY = 2;
    public static final short DEFAULT_AWAKE_DUTY_CYCLE = 8000;
    public static final byte COMMAND_REQUEST = 2;
    public static final byte QUERY_REQUEST = 1;
    public static final byte CMD_SET_AWAKE_DUTY_CYCLE = 1;
    public static final short AM_DISON_USER_REQUEST = 145;
    public static final byte AUTO_TEST_DIS_KEY = 50;
    public static final int AUTO_TEST_TIME = 300000;
    public static final byte SENSOR_LIGHT = 4;
    public static final byte CMD_GET_TOPO = 3;
    public static final byte CMD_RESET_NETWORK = 2;
    public static final byte MAX_PARAMS = 10;
    public static final short AM_DISON_TEST = 144;
    public static final byte QUERY_REQUEST_DIS_KEY = 48;
    public static final byte LOG_RETRY_MAX = 3;
    public static final byte AUTOTEST_REQUEST = 3;
    public static final short LOG_SEND_TIME = 10000;
    public static final byte MAX_RUN_TIMES = 2;
    public static final byte SENSOR_TEMPERATURE = 1;
    public static final byte DEFAULT_QUERY_PERIOD = 5;
}
