/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'DisonTopoMsg'
 * message type.
 */

public class DisonTopoMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 53;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 147;

    /** Create a new DisonTopoMsg of size 53. */
    public DisonTopoMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new DisonTopoMsg of the given data_length. */
    public DisonTopoMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DisonTopoMsg with the given data_length
     * and base offset.
     */
    public DisonTopoMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DisonTopoMsg using the given byte array
     * as backing store.
     */
    public DisonTopoMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DisonTopoMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public DisonTopoMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DisonTopoMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public DisonTopoMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DisonTopoMsg embedded in the given message
     * at the given base offset.
     */
    public DisonTopoMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DisonTopoMsg embedded in the given message
     * at the given base offset and length.
     */
    public DisonTopoMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <DisonTopoMsg> \n";
      try {
        s += "  [id=0x"+Long.toHexString(get_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [noNodes=0x"+Long.toHexString(get_noNodes())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nodeList=";
        for (int i = 0; i < 25; i++) {
          s += "0x"+Long.toHexString(getElement_nodeList(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: id
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'id' is signed (false).
     */
    public static boolean isSigned_id() {
        return false;
    }

    /**
     * Return whether the field 'id' is an array (false).
     */
    public static boolean isArray_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'id'
     */
    public static int offset_id() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'id'
     */
    public static int offsetBits_id() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'id'
     */
    public int get_id() {
        return (int)getUIntBEElement(offsetBits_id(), 16);
    }

    /**
     * Set the value of the field 'id'
     */
    public void set_id(int value) {
        setUIntBEElement(offsetBits_id(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'id'
     */
    public static int size_id() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'id'
     */
    public static int sizeBits_id() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: noNodes
    //   Field type: short, unsigned
    //   Offset (bits): 16
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'noNodes' is signed (false).
     */
    public static boolean isSigned_noNodes() {
        return false;
    }

    /**
     * Return whether the field 'noNodes' is an array (false).
     */
    public static boolean isArray_noNodes() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'noNodes'
     */
    public static int offset_noNodes() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'noNodes'
     */
    public static int offsetBits_noNodes() {
        return 16;
    }

    /**
     * Return the value (as a short) of the field 'noNodes'
     */
    public short get_noNodes() {
        return (short)getUIntBEElement(offsetBits_noNodes(), 8);
    }

    /**
     * Set the value of the field 'noNodes'
     */
    public void set_noNodes(short value) {
        setUIntBEElement(offsetBits_noNodes(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'noNodes'
     */
    public static int size_noNodes() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'noNodes'
     */
    public static int sizeBits_noNodes() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nodeList
    //   Field type: int[], unsigned
    //   Offset (bits): 24
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nodeList' is signed (false).
     */
    public static boolean isSigned_nodeList() {
        return false;
    }

    /**
     * Return whether the field 'nodeList' is an array (true).
     */
    public static boolean isArray_nodeList() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'nodeList'
     */
    public static int offset_nodeList(int index1) {
        int offset = 24;
        if (index1 < 0 || index1 >= 25) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nodeList'
     */
    public static int offsetBits_nodeList(int index1) {
        int offset = 24;
        if (index1 < 0 || index1 >= 25) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'nodeList' as a int[]
     */
    public int[] get_nodeList() {
        int[] tmp = new int[25];
        for (int index0 = 0; index0 < numElements_nodeList(0); index0++) {
            tmp[index0] = getElement_nodeList(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'nodeList' from the given int[]
     */
    public void set_nodeList(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_nodeList(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'nodeList'
     */
    public int getElement_nodeList(int index1) {
        return (int)getUIntBEElement(offsetBits_nodeList(index1), 16);
    }

    /**
     * Set an element of the array 'nodeList'
     */
    public void setElement_nodeList(int index1, int value) {
        setUIntBEElement(offsetBits_nodeList(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'nodeList'
     */
    public static int totalSize_nodeList() {
        return (400 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'nodeList'
     */
    public static int totalSizeBits_nodeList() {
        return 400;
    }

    /**
     * Return the size, in bytes, of each element of the array 'nodeList'
     */
    public static int elementSize_nodeList() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'nodeList'
     */
    public static int elementSizeBits_nodeList() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'nodeList'
     */
    public static int numDimensions_nodeList() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'nodeList'
     */
    public static int numElements_nodeList() {
        return 25;
    }

    /**
     * Return the number of elements in the array 'nodeList'
     * for the given dimension.
     */
    public static int numElements_nodeList(int dimension) {
      int array_dims[] = { 25,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
